selected_scheme scheme-basic
TEXDIR $CI_PROJECT_DIR/.cache/texlive
TEXMFCONFIG ~/.texlive/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL $CI_PROJECT_DIR/.cache/texlive/texmf-local
TEXMFSYSCONFIG $CI_PROJECT_DIR/.cache/texlive/texmf-config
TEXMFSYSVAR $CI_PROJECT_DIR/.cache/texlive/texmf-var
TEXMFVAR ~/.texlive/texmf-var
option_doc 0
option_src 0
