selected_scheme scheme-basic
TEXDIR /tmp/.cache/texlive
TEXMFCONFIG ~/.texlive/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /tmp/.cache/texlive/texmf-local
TEXMFSYSCONFIG /tmp/.cache/texlive/texmf-config
TEXMFSYSVAR /tmp/.cache/texlive/texmf-var
TEXMFVAR ~/.texlive/texmf-var
option_doc 0
option_src 0
